// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vquoontqioxymidkgtqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxdW9vbnRxaW94eW1pZGtndHFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTY3NjEsImV4cCI6MjA3MDI5Mjc2MX0.ogdZ9SiMhK9Qa5CaU4ZkEIPX95V_Xunw00uooATHNxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});